/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bank.accounts.application.api;

import com.bank.accounts.application.schemas.request.AccountRequest;
import com.bank.accounts.application.schemas.request.CreateAccountCardRequest;
import com.bank.accounts.application.schemas.response.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-18T07:29:52.914264900-05:00[America/Lima]")
@Validated
@Tag(name = "accounts", description = "the accounts API")
public interface AccountsApi {

    /**
     * POST /accounts : Crear Cuenta
     *
     * @param accountRequest (required)
     * @return (status code 200)
     * or  (status code 202)
     * or  (status code 400)
     * or  (status code 500)
     */
    @Operation(
            operationId = "createAccount",
            summary = "Crear Cuenta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "202", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TrackingResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/accounts",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    Mono<TrackingResponse> createAccount(
            @Parameter(name = "AccountRequest", description = "", required = true) @Valid @RequestBody Mono<AccountRequest> accountRequest,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * POST /accounts/{accountId}/cards : Crear Cuenta Tarjeta
     *
     * @param accountId                (required)
     * @param createAccountCardRequest (required)
     * @return (status code 200)
     * or  (status code 202)
     * or  (status code 400)
     * or  (status code 404)
     * or  (status code 500)
     */
    @Operation(
            operationId = "createAccountCard",
            summary = "Crear Cuenta Tarjeta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "202", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TrackingResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/accounts/{accountId}/cards",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    Mono<TrackingResponse> createAccountCard(
            @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") Long accountId,
            @Parameter(name = "CreateAccountCardRequest", description = "", required = true) @Valid @RequestBody Mono<CreateAccountCardRequest> createAccountCardRequest,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * DELETE /accounts/{accountId} : Borrar Cuenta
     *
     * @param accountId (required)
     * @return (status code 200)
     * or  (status code 202)
     * or  (status code 400)
     * or  (status code 404)
     * or  (status code 500)
     */
    @Operation(
            operationId = "deleteAccount",
            summary = "Borrar Cuenta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "202", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TrackingResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/accounts/{accountId}",
            produces = {"application/json"}
    )
    Mono<TrackingResponse> deleteAccount(
            @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") Long accountId,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * DELETE /accounts/{accountId}/cards/{cardId} : Borrar Cuenta Tarjeta
     *
     * @param accountId (required)
     * @param cardId    (required)
     * @return (status code 200)
     * or  (status code 202)
     * or  (status code 400)
     * or  (status code 404)
     * or  (status code 500)
     */
    @Operation(
            operationId = "deleteAccountCard",
            summary = "Borrar Cuenta Tarjeta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "202", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TrackingResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/accounts/{accountId}/cards/{cardId}",
            produces = {"application/json"}
    )
    Mono<TrackingResponse> deleteAccountCard(
            @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") Long accountId,
            @Parameter(name = "cardId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("cardId") Long cardId,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * PUT /accounts/{accountId}/cards/{cardId} : Actualizar Cuenta Tarjeta
     *
     * @param accountId                (required)
     * @param cardId                   (required)
     * @param createAccountCardRequest (required)
     * @return (status code 200)
     * or  (status code 202)
     * or  (status code 400)
     * or  (status code 404)
     * or  (status code 500)
     */
    @Operation(
            operationId = "editAccountCard",
            summary = "Actualizar Cuenta Tarjeta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "202", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TrackingResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/accounts/{accountId}/cards/{cardId}",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    Mono<TrackingResponse> editAccountCard(
            @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") Long accountId,
            @Parameter(name = "cardId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("cardId") Long cardId,
            @Parameter(name = "CreateAccountCardRequest", description = "", required = true) @Valid @RequestBody Mono<CreateAccountCardRequest> createAccountCardRequest,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * GET /accounts/{accountId} : Obtener Cuenta
     *
     * @param accountId (required)
     * @return (status code 200)
     * or  (status code 400)
     * or  (status code 404)
     * or  (status code 500)
     */
    @Operation(
            operationId = "obtainAccount",
            summary = "Obtener Cuenta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "200", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = AccountResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/accounts/{accountId}",
            produces = {"application/json"}
    )
    Mono<AccountResponse> obtainAccount(
            @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") Long accountId,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );


    /**
     * PUT /accounts/{accountId} : Actualizar Cuenta
     *
     * @param accountId      (required)
     * @param accountRequest (required)
     * @return (status code 200)
     * or  (status code 202)
     * or  (status code 400)
     * or  (status code 404)
     * or  (status code 500)
     */
    @Operation(
            operationId = "updateAccount",
            summary = "Actualizar Cuenta",
            description = "",
            tags = {},
            responses = {
                    @ApiResponse(responseCode = "202", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = TrackingResponse.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestResponse.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundResponse.class))
                    }),
                    @ApiResponse(responseCode = "500", description = "", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = InternalErrorResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/accounts/{accountId}",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    Mono<TrackingResponse> updateAccount(
            @Parameter(name = "accountId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("accountId") Long accountId,
            @Parameter(name = "AccountRequest", description = "", required = true) @Valid @RequestBody Mono<AccountRequest> accountRequest,
            @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
